### ISSUE TITLE
Super+w doesn't work on BL-Lithium ARM install...

### ISSUE THREAD

**Issue by bsbens** [BunsenLabs/bunsen-configs#101]
Hey guys,
Hope I'm not OT.
Installed Lithium packages (arch all) over Raspbian Buster Lite (Openbox, LAMP).
Long but pretty easy install.
If I'm not mistaken, the Super+w combo does not work for me... Tried to edit the .xbindkeysrc file but it seems like it's not the one read by the system i.e changed the "x-www-browser" command to "firefox" or "firefox-esr" but nothing changes... Am I doing something wrong?

**Comment by johnraff** [comment]
The keybinds appear to be working for other people.
Please post a support request on the BunsenLabs forum if the problem persists: https://forums.bunsenlabs.org/viewforum.php?id=2

Closing this issue.
