### ISSUE TITLE
Change directory 

### ISSUE THREAD

**Issue by rbh-se** [BunsenLabs/bunsen-configs#113]
https://github.com/BunsenLabs/bunsen-configs/blob/1118c09a4a8d5ab82d2d7c0b7d42069184c48aa3/skel/.config/jgmenu/prepend.csv#L141

Looks for filename="/usr/share/bunsen/docs/helpfile-bl-alternatives.txt", but Package bunsen-docs 11.1-1 puts helpfile-bl-alternatives.txt in directory /usr/share/bunsen/docs/helpfiles, so the menu-choise "About Bunsen Alternatives", launch an empty yad.

**Comment by johnraff** [comment]
Thank you for catching this! Now fixed in commit df684d1

(There were some old filepaths in other packages too.)
