### ISSUE TITLE
Tint2 gitlab has new adress

### ISSUE THREAD

**Issue by rbh-se** [BunsenLabs/bunsen-configs#114]
So, the adress in the text: 
#---- Generated by tint2conf 0320 ----
# See https://gitlab.com/o9000/tint2/wikis/Configure for

Has to be changed to:
# See https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md

**Comment by johnraff** [comment]
Thank you for catching this. 

By searching the repository I identified the files you are referring to as being the various tint2rc under skel/.config/tint2/ and skel-lite/skel/.config/tint2/

**Comment by rbh-se** [comment]
I close this, have pushed the change.
