### ISSUE TITLE
add menu for hw-probe

### ISSUE THREAD

**Issue by rbh-se** [BunsenLabs/bunsen-configs#116]
Many users won't know that hw-probe is installed, if there is no menu choise.
i propose to add the following menus in prepend.csv, under ^tag(bl-system).

* hw-probe - system report saved local  
Command to be issued:  
sudo -E hw-probe -all

* hw-probe - system report uploaded  
Command to be issued:  
sudo -E hw-probe -all  -upload

Mayby a link to "man hw-probe" and/or link to https://github.com/linuxhw/hw-probe

**Comment by johnraff** [comment]
This is a problem that BL has been struggling with for years - what is the best compromise between hard-coded menu items and autogenerated pipemenus?

The former are easily edited by users, but the latter often do not need to be edited at all.

Menu items for applications that are not installed are annoying for users.

Previously, we had some pipemenus, eg "graphics pipemenu" which looked like the system>Install Favourite Packages menu, but if it found an app to be installed it showed the menu item. This has the disadvantage of being out of the user's control, and also not appearing in jgmenu searches, so we are now trying to reduce the number of pipemenus.

---
I have just had an idea that the "install" script might be able to offer to add a menu item for the installed package directly to the user's prepend.csv. That would get round both issues, but would need some work, so would not be able to go in the Boron release.

Please post a new topic in the [BL forums](https://forums.bunsenlabs.org/viewforum.php?id=13) if you would like to discuss this further.

**Comment by rbh-se** [comment]
[Posting done](https://forums.bunsenlabs.org/viewtopic.php?pid=129021#p129021). 
Closing this issue.
