### ISSUE TITLE
Jgmenu systemreport shows too little information

### ISSUE THREAD

**Issue by rbh-se** [BunsenLabs/bunsen-configs#117]
was a while since I last used "Quick System Info".
Now the information is very sparse. 
On Boron system with version 12,0-1, inxi behaves as expected

**Comment by johnraff** [comment]
Where are you seeing this "very sparse" inxi output? I just checked on Beryllium and Boron systems and in both cases the "Quick System Info" menu item worked correctly.

**Comment by rbh-se** [comment]
In the terminal of course...

But, that was weird.
I had this issue on my laptop and the desktop. Jgmenu => "Quick System Info,", gave sparse info, same as the command "inxi", without flags.
An Boron VM, with bunsen-configs 12,0-1, was ok before upgrading, but not after.

I now tested on the newly net-installed boron vm. 
There it was ok.
So, it must for some reason be something specific for my installations. 
The prepend.csv, is ok. Whatever reason, it is no problem with the package.
I close this issus.

//regards
