### ISSUE TITLE
menu.xml references to geany

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#12]
There are still many geany references. Should we be using xdg-open, or whatever is to be used for "bl-text-editor"?

**Comment by johnraff** [comment]
The best option will be **bl-text-editor** itself, which will be an executable, set up in the Debian alternatives system. Also available will be bl-file-manager, bl-image-viewer and bl-media-player, along with the Debian standards x-terminal-emulator and x-www-browser. All that config will be going into bunsen-configs in a few days - after I've finished hacking up bl-welcome! 

If you have the time, please feel free to change all references to specific applications in menu.xml, rc.xml and pipemenus accordingly. (I was going to do it later.) They won't work until the _alternatives_ are also in place of course.

**Comment by capn-damo** [comment]
I'm on  it :)

**Comment by capn-damo** [comment]
What would be the correct change for eg `if [[ -x /usr/bin/geany ]];then...`?

EDIT:

Using a symlink (`ln -s /usr/bin/geany bin/bl-text-editor`) for testing, the following works:
`if ! bl-text-editor "file/to/edit";then`

**Comment by johnraff** [comment]
For testing, you could put all those bl-\* things in your ~/bin as symlinks to the actual apps so they're in your path, and all files (menu etc) should work exactly as if the real /usr/bin/bl-\* alternatives had been installed. (They are also symlinks, first to files in /etc/alternatives which themselves are symlinks to the real apps.)

You don't need to use full paths. That leaves room for users to put symlinks in their own ~/bin to divert the alternative if they don't want to make a system-wide change.

`[[ -x bl-text-editor ]]` doesn't work without a full path though. To test if a command executes something, how about replacing that test with `if type bl-text-editor >/dev/null;` or `if hash bl-text-editor >/dev/null;` ?

**Comment by capn-damo** [comment]
I suppose the test I used ^ would fail if there was a problem with EITHER bl-text-editor OR the file?

I wasn't sure if you could treat eg `bl-text-editor` like a regular file for a test. I'll try the other ways you mentioned.

**Comment by johnraff** [comment]
You can regard bl-text-editor as a command. It's a symlink in $PATH (/usr/bin) so it looks just like any other command. 

For example, `[[ -x /usr/bin/x-terminal-emulator ]] && echo yes` returns yes, though  `type x-terminal-emulator >/dev/null && echo yes`  covers cases where the symlink is somewhere else, like ~/bin.
