### ISSUE TITLE
prepend.csv: Illegal quoting in line 6

### ISSUE THREAD

**Issue by yecril23pl** [BunsenLabs/bunsen-configs#129]
This is not a valid CSV record:

> \## See more info with command 'bl-user-setup --help'

**Comment by johanmalm** [comment]
It's legal jgmenu-flavoured CSV which is what matters.

Github tries to show `prepend.csv` in table format, but considering the type of markup we do (e.g. `^foo()` and `@widget`) I think table format is undesirable.

**Comment by yecril23pl** [comment]
Requires https://github.com/jgmenu/jgmenu/issues/219

**Comment by johanmalm** [comment]
@yecril23pl Please stop time-wasting and be a force for good instead.
