### ISSUE TITLE
~/.conkyrc needs to be a symlink to BL default conky

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#18]
`~/.conkyrc` should be a symlink to `~/.config/conky/BL-Default.conkyrc`. (Conkys aren't installed)

**Comment by johnraff** [comment]
Yes. Something that slipped by.

1) I need to check if symlinks can be installed by .deb files, or if it needs a postinst script.
EDIT This seems to be it: http://forums.debian.net/viewtopic.php?f=8&t=73664#p409413

2) ~/.config/conky/BL-Default.conkyrc is installed by bunsen-conky atm. I guess that one file needs to be moved to bunsen-configs for people who don't install bunsen-conky. (The same file can't be installed by two different packages.)

**Comment by johnraff** [comment]
~/.conkyrc is now a _copy_ of ~/.config/conky/BL-Default.conkyrc
