### ISSUE TITLE
Wifi connections/ disconnects

### ISSUE THREAD

**Issue by Zeitvertreib** [BunsenLabs/bunsen-configs#20]
Internet via Cable, runs just fine.
Internet via Wifi at University (WPA2 TTSL PAP and a certificate), runs just fine.
Internet via Wifi at home (WPA2), disconnects (or hooks up) after seconds. (Networkmanager says yes, ping google says no)

Other mashines are doin fine at home.. (Manjaro, #!)

Running Bunsen on my newly bought old and used Lenovo x60s (testing purpose mashine).

Not sure, if it is an issue or just odd. I might solve this at a given time on my own, but since the overall setting works for me, it might take some time.

Edit: not sure, if to place on 'netinstall' (because this concerned the situation after the netinstallscript)

**Comment by johnraff** [comment]
@Zeitvertreib It's not clear if this is an issue with bunsen-configs, with bunsen-netinstall or even with the BunsenLabs setup at all. It sounds like a wireless networking issue  possibly related to your card or your home network.

If you would like help in resolving your problem I suggest you ask on the CrunchBang forums, where BunsenLabs is also being discussed: http://crunchbang.org/forums/viewforum.php?id=22
There are more people there with wireless networking knowlege who might be able to help you.

**Comment by Zeitvertreib** [comment]
nope, can't recover my password on #! forums, nor can I create a new account. Also wrote an email to corenominal@crunchbanglinux.org, got no response. (i did not get an email to reset my pw)

**Comment by ghost** [comment]
On Sat, Jun 06, 2015 at 12:23:51AM -0700, Zeitvertreib wrote:

> Meanwhile I reproduced (reinstalled) but in addition installed another debian
> based distro on the same machine.

Please do open a thread on the forums (from whatever account, I can't help you
here), people will ask for relevant information and help you bisect the issue.

> But the other distro doesn't have the issue. I understand that this might be
> not solved right away and that it might be an individual thing.

Regardless of what "other distro" you are referring to, it's probably a
configuration issue. As no size fits all, most Linux problems are "individual
problems" anyway :)
