### ISSUE TITLE
Nitrogen path in menu.xml

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#25]
From this post in the CB forums: http://crunchbang.org/forums/viewtopic.php?pid=433635#p433635

> If I may offer a gentle suggestion, please please please don't hard-code the wallpaper path in Bunsen's menu.xml. I know #! did this, but it caused a lot of problems and repeated help topics (and has continued to cause problems for the OP). If you need to set the initial path, put it in the config file (~/.config/nitrogen/nitrogen.cfg) and simply call "nitrogen" in menu.xml -- this way when the user changes the path or adds directories the changes will persist.

**Comment by johnraff** [comment]
Sounds like a very good idea. We'd need to add a line to nitrogen.cfg like 
`dirs=/home/john/Pictures/wallpapers;`
The only snag is that it has to be the full path and ~/ or $HOME are not recognized. The installer would have to write in the correct path for that user. It's not impossible though.

**Comment by johnraff** [comment]
Done.
