### ISSUE TITLE
autostart needs updating

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#26]
autostart has

> `#(sleep 2; tint2) &`
> `## To start a saved tint2 session,  comment out the line above, and uncomment:`
> `(sleep 2s && bl-tint2-session) &`
> `## Run the conky`
> `#conky -q &`
> `## To start a saved Conky session, comment out the line above, and uncomment:`
> `(sleep 2s && bl-conky-session --autostart) &`

Should it be something like:

> `## Start the tint2 session (the default tint2 will run if no sessions have been set)`
> `(sleep 2s && bl-tint2-session) &`
> `## Start the Conky session (the default conkyrc will run if no sessions have been set)`
> `(sleep 2s && bl-conky-session --autostart) &`

Also there is something I always want to add - HorizEdgeScroll:

> `## Detect and configure touchpad. See 'man synclient' for more info.`
> `if egrep -iq 'touchpad' /proc/bus/input/devices; then`
> `synclient VertEdgeScroll=1 &`
> `synclient HorizEdgeScroll=1 &`
> `synclient TapButton1=1 &`
> `fi`

I wasn't going to push any changes without some feedback ;)

**Comment by hhhorb** [comment]
Fine by me, this is up to you and John, as far as I'm concerned. :)

**Comment by johnraff** [comment]
Looks good to me.
(btw I wonder if the syntax for bl-tint2-session and bl-conky-session could be unified? Is there a reason why the --autostart option is needed in conky's case?)

There are some other tweaks coming in the next version of bunsen-configs, so I'll push it when everything's ready.

**Comment by johnraff** [comment]
Anyway, autostart is now edited at this end. Upload coming in a day or two.

**Comment by capn-damo** [comment]
Ref `bl-conky-session --autostart`. It runs the sessionfile or default conkyrc without asking if running conkys should all be stopped first. I guess it would be possible to test for a firstrun case, but it was an easy way for me to set a flag
`if [[ $arg = "--autostart" ]];then`
           `arg="$SESSIONFILE"`
           `NOKILL=1    # run from autostart, so don't ask to kill conkys`
       `fi`
