### ISSUE TITLE
Tweak default compton shadow settings?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-configs#29]
A very small issue, but I find the default compton shadows to be too big, and dispersed equally round the window. I think they'd look better a bit off to the right and down, and a bit smaller. This can all be achieved by uncommenting three lines in skel/.config/compton.conf thus:

```
# Shadow
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
#clear-shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.4;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
#shadow-exclude = [ "n:e:xfce4-notifyd", "i:e:Conky" ];
shadow-exclude = [ "i:e:Conky" ];
#shadow-ignore-shaped = false;
```

Does that sound OK?

**Comment by hhhorb** [comment]
Agreed, the current shadows are too heavy. Nice catch!

**Comment by johnraff** [comment]
OK done. 
**bunsen-configs** will get a few more tweaks so I haven't pushed the version number yet.
