### ISSUE TITLE
`.config/openbox/menu.xml` scrot -- no `~/image` directory

### ISSUE THREAD

**Issue by smacz42** [BunsenLabs/bunsen-configs#3]
On my jessie netinstall, I did not import the #! $HOME directories and left them as the vanilla Debian default setup. This includes a `Pictures` directory, but not an `images` directory. The `scrot` commands in the openbox menu rely on there being a `images` directory, for instance:

```
scrot '%Y-%m-%d--%s_$wx$h_scrot.png' -e 'mv $f ~/images/ &amp; viewnior ~/images/$f'
```

IIRC @johnraff indicated on the #! forums that the directory structure was to be the same as the Debian defaults for a user's `$HOME` to preserve interoperability (or something like that). If that's true, should the `images` directory reference be changed to `Pictures`? I wanted to ask before I went ahead and submitted a pull request as I'm not able to find the post where @johnraff had indicated we were to preserve the vanilla directory structure.

EDIT: Also present in `.config/openbox/rc.xml`

**Comment by johnraff** [comment]
The "Pictures" directory will be created automatically by xdg-user-dirs, and "images" will be installed by the bunsen-configs package, along with the menu.xml and rc.xml files that refer to it, so there will be no errors. Do you think "images", or perhaps "screenshots", should be a subfolder of "Pictures"?

Personally, I think "images" evokes a wider range of files, including icons avatars etc, while "Pictures" suggests photographs. How the user eventually uses the two folders is of course up to him/her. The forum discussion never really reached a firm conclusion on that point, so for the moment I left "images" in.

BTW thanks to your post I've just noticed that the menu entries put screenshots in "images" while the keyboard shortcuts in rc.xml put them in "images/screenshots". That will have to be fixed anyway.

**Comment by smacz42** [comment]
The forum discussion indeed did not reach any sort of firm conclusion. Also, I'm unsure if there are any other commands that may point to a `~/images` directory. Of course if I find any I will report them as such. 

Besides the menu/rc.xml discrepancy, for me this distills down to adhering to the vanilla debian `$HOME` directory defaults versus customizing it for this BunsenLabs distro. The commands can be changed either way; the philosophy...not so much. This is (as someone who was getting paid to do this might say) above my pay grade. I would respectfully defer to whatever was deemed the morally correct way to setup the defaults on BunsenLabs.

I do like the idea of having the screenshots as a submenu though. (~/{images | Pictures}/screenshots/)

**Comment by johnraff** [comment]
I'll check back with the other devs and see if we can get to a decision on this.

**Comment by capn-damo** [comment]
I added a test to the bl-graphics-pipemenu, to use xdg-user-dir PICTURES, so whatever is set there is used (~/images, ~/Pictures, etc). And mkdir screenshots if necessary.

**Comment by ghost** [comment]
Well can we close this then?

**Comment by johnraff** [comment]
Yes.
