### ISSUE TITLE
Move skel/.fonts to skel/.local/share/fonts?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-configs#31]
The user ~/.fonts directory is deprecated (see /etc/fonts/fonts.conf) and the [xdg approved](http://www.freedesktop.org/software/fontconfig/fontconfig-user.html) default location is ~/.local/share/fonts.

The directory is empty anyway, so another alternative would be to remove it and leave it up to the user to put it in the right place.

**Comment by capn-damo** [comment]
May as well sort it out now, so we all get used to it.

I guess when giving advice you just say "Copy your downloaded font into ~/.local/share/fonts (create the directory if it doesn't already exist)"

**Comment by johnraff** [comment]
OK let's be kind and create an empty directory there.

...in fact, it looks as if icons and themes should now be in ~/.local/share/ also.

Since they're all empty when we ship BL we might as well put them in the approved place from the start I guess. It makes the HOME directory a bit cleaner.

**Comment by capn-damo** [comment]
^ I was just checking the situation with .icons and .themes myself :)

Yes, let's have empty dirs there.

**Comment by hhhorb** [comment]
I thought it was just the gtk3 index file that should go in ~/.local/share/themes, the rest of the theme stays in ~/.themes (if not in /usr/share/themes).

Anyway, +1 on the font relocation, I was just thinking this yesterday when installing some fonts.

**Comment by johnraff** [comment]
> I thought it was just the gtk3 index file that should go in ~/.local/share/themes, the rest of the theme stays in ~/.themes (if not in /usr/share/themes).

That doesn't sound right somehow. [eg XFCE wiki](https://wiki.xfce.org/howto/install_new_themes)
I'll move one of my personal theme folders from ~/.themes to ~/.local/share/themes and check if it still gets recognized OK. 

Anyway these are just empty directories for user-installed stuff, /usr/share/themes stays the same.

**Comment by hhhorb** [comment]
From my looks of my latest fresh install, this has all been fixed now via symlinks. Yes?

**Comment by johnraff** [comment]
Yes. Some apps were slow to adapt to the new locations, so symlinks were needed too. Maybe in the future they can be removed.
