### ISSUE TITLE
tint2rc systray background too dark

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#32]
The dark icons for power and network are invisible against the default dark tint2 background. 

Suggest changing to `systray_background_id = 2`, which is the same as that used by `task_active_background_id`

**Comment by hhhorb** [comment]
Fine by me.

**Comment by johnraff** [comment]
Which are these "dark icons"? The default light grey faenza are visible.

btw I see no difference between faenza-bunsen and faenza-dark-bunsen in most situations.

**Comment by hhhorb** [comment]
> I see no difference between faenza-bunsen and faenza-dark-bunsen in most situations

I was going to bring this up, it doesn't seem like the bunsen icons were packaged correctly. For example, installing faenza-icon-theme from jessie instantly solves the invisible pnmixer icon (probably volumeicon too).

I'll see what I can find and post back.

**Comment by johnraff** [comment]
> I'll see what I can find and post back.

Please.

Although, I saw the same lack of difference when on #! too. At that time I seem to remember being told the "dark" meant that the icons were meant for use on dark backgrounds, rather than that they were dark themselves.

**Comment by hhhorb** [comment]
> I'll see what I can find and post back.

https://github.com/2ion/bunsen-org/issues/107#issue-112065606

> Although, I saw the same lack of difference when on #! too

Maybe Philip's error that we've carried over, then.

> At that time I seem to remember being told the "dark" meant that the icons were meant for use on dark backgrounds, rather than that they were dark themselves.

This is correct, "Faenza-Bunsen-Dark" should be the default icon theme for use with our tint2conf.

**Comment by johnraff** [comment]
I remember having to use "dark" at some point to make a volume icon visible.

**Comment by johnraff** [comment]
I think this issue might be fixed by the icon repackaging @hhhorb suggested elsewhere. If we provide only the folder icons and inherit the rest from Faenza some things will become simpler.

> "Faenza-Bunsen-Dark" should be the default icon theme for use with our tint2conf.

This is how BL is configured OOTB. ("Faenza-Dark-Bunsen" that is)

**Comment by johnraff** [comment]
Icon theme discussion here: https://github.com/BunsenLabs/bunsen-faenza-icon-theme/issues/2
