### ISSUE TITLE
Openbox titlebar window icon

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#33]
The default `rc.xml` has no entry for a window icon: `<titleLayout>DSLIMC</titleLayout>`;
instead of: `<titleLayout>NDSLIMC</titleLayout>`

Is this the intended setting? If so, what is the argument for not having a window icon button (because I would like to have it by default ;) )?

**Comment by johnraff** [comment]
It's the inherited setting from Crunchbang, so I guess Philip preferred it that way. 

I have the window icon enabled at the moment, but I have no opinion either way on what should be the default.

Ask on the forum?
Or, just follow the principle of 'put stuff in and let users take out what they don't want'?

**Comment by hhhorb** [comment]
However you guys want to handle it.

**Comment by capn-damo** [comment]
If there is no further objection I'll edit the `<titleLayout>` in `/usr/share/bunsen/skel/.config/openbox/rc.xml`

**Comment by johnraff** [comment]
Please go ahead. It's easy enough to change back.

**Comment by capn-damo** [comment]
Added "N" to `<titleLayout>`

Pushed change to `skel/.config/openbox/rc.xml`
