### ISSUE TITLE
hsetroot in autostart

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-configs#34]
autostart includes a commented line for an hsetroot command, but it isn't installed

```
## Set root window colour
#hsetroot -solid "#2E3436" &
```

**Comment by hhhorb** [comment]
Yeah, that's #! cruft. It didn't make sense to me to both set hsetroot and use nitrogen --restore so I didn't include hsetroot in the package list. Do you want to clean up autostart or leave it in as a little puzzle?

**Comment by capn-damo** [comment]
> Do you want to clean up autostart or leave it in as a little puzzle?
> :yum: 

That does appeal to me, but think that to be tidy it should be removed. Or add hsetroot to the package list? See what others think....

**Comment by johnraff** [comment]
Let's take those lines out.

**Comment by hhhorb** [comment]
Agreed. Push it and close, thanks gentlemen!

**Comment by johnraff** [comment]
There are some other things to tidy up in bunsen-configs, so the push will take a bit...

**Comment by hhhorb** [comment]
Just tidying up. Close this?

**Comment by johnraff** [comment]
> Just tidying up.

Good idea, and yes that's been done.
