### ISSUE TITLE
Keyboard support for volume mute toggle

### ISSUE THREAD

**Issue by Head-on-a-Stick** [BunsenLabs/bunsen-configs#35]
Related to the known issue of volti failing to un-mute from the icon, should we add an `amixer` keybind in **skel/.config/openbox/rc.xml**?

For example:

`<keybind key="XF86AudioMute">`
`  <action name="Execute">`
`    <command>amixer set -D pulse Master toggle</command>`
`  </action>`
`</keybind>`

See:
https://forums.bunsenlabs.org/viewtopic.php?id=537
https://forums.bunsenlabs.org/viewtopic.php?id=747

**Comment by 2ion** [comment]
This is very ugly. I'd rather build a backported version – for a good reason, methinks?

**Comment by Head-on-a-Stick** [comment]
I would agree but what about users who prefer not to use backported packages?

**Comment by johnraff** [comment]
Is volti the cause, not xfce4-volume-daemon?
Is the volti-or-not-as-default-mixer issue not dead after all? pasystray?

**Comment by hhhorb** [comment]
xfce4-volumed-pulse is the answer here, I think, now that xfce4-volumed has been removed from sid due to it's pulse failings. A backport, so it should be a bl-welcome option full of Stern Warnings.

I've backported it once, I'll look for it again and post back.

**Comment by johnraff** [comment]
Might xfce4-volumed-pulse finally make Volti work OK?
fingers crossed...

**Comment by hhhorb** [comment]
Give me a few hours. *boots into BL*

**Comment by hhhorb** [comment]
Blech. I already had installed an Ubuntu backport on a brand new install and it was working fine. Now it didn't. I removed it and installed our backport and it's working great now.

Can we port this whole project over to MATE? :^D

**Comment by johnraff** [comment]
> installed our backport and it's working great (with volti) now.

What backport was that? Are we OK with the packages as-is for the RC2 iso?

**Comment by hhhorb** [comment]
^Our xfce4-volumed backport. On my hardware it solves the problem of mute/unmute via my keyboard volume buttons but unmuting by clicking the icon fails (the icon highlight state changes but I still have to press my mute key to unmute sound.

Honestly, I don't think there's anything we can do, xfce4-volumed in jessie isn't the greatest.

**Comment by johnraff** [comment]
Drag. So if even the backport doesn't fix the icon-click muting, shall we just leave it as as something to suggest on the furum?

And, yes, after the first release is out (?) let's have a serious think about if incorporating some items from MATE would improve things.

**Comment by hhhorb** [comment]
^Yes and yes!

**Comment by johnraff** [comment]
For the RC2 I could throw H-o-a-S's keybind into bunsen-configs : https://github.com/BunsenLabs/bunsen-configs/issues/35#issue-119887624

There is other stuff in b-c to be comitted anyway.

**Comment by hhhorb** [comment]
That's fine.

**Comment by johnraff** [comment]
OK done.
