### ISSUE TITLE
fdpowermon config file points to non-existing icons

### ISSUE THREAD

**Issue by tdanhorn** [BunsenLabs/bunsen-configs#36]
The default `~/.config/fdpowermon/theme.cfg` (from `skel`) contains the line `dir = /usr/share/icons/Faenza-Dark-Bunsen/status/22/`, and it expects icons named `gpm-primary-??0-charging.png` there.  Since the cleanup of the BunselLabs incon themes (which made use of inheritance from the Faenza themes), these icons were removed from the Bunsen-specific directories and exist in only `/usr/share/icons/Faenza-Dark/status/22/`, and the space in the tint2 panel used by fdpowermon is blank (but shows battery stats on mouse-over).
fdpowermon is a rather simple script and I consider it unlikely that the maintainer would change it any time soon to follow the freedesktop.org icon theme specification (which might well double the code).  In any case, the config file asks for a directory, not a theme name, and its icon theme is not linked to anything in Preferences->Appearance.  So I think the easy fix is to point `theme.cfg` to `/usr/share/icons/Faenza-Dark/status/22/`.  (BTW, the live CD still has the pre-cleanup icon setup, so it works -- at the expense of duplicating icons.)  Thanks for all the hard work and continuing the #! spirit!

**Comment by johnraff** [comment]
@tdanhorn Thank you for catching this!
Since fdpowermon requires a hard-coded icon directory, your solution does seem the best way to go.

Now pushed in  **bunsen-configs 8.6.7-1**.
