### ISSUE TITLE
openbox/menu.xml: paths to some helpfiles are wrong

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-configs#42]
Attached fix in pull request #41.

Does the package index get refreshed for new BL installs before installation stuff to disk?

In any case, we should fix this ASAP because it's clearly user-facing.

**Comment by johnraff** [comment]
Merged, changelog updated and tagged to **8.7.1-1**

And thank you for catching this!

> Does the package index get refreshed for new BL installs before installation stuff to disk?

You'll have to check with @hhhorb but AFAIK no. I think the packages are baked into the iso at the time it is built. A dynamic install of the bunsen-\* packages from the BL repository at install time (like the netinstall) might conceivably be possible, but I don't know how a live session would work in that case - we'll have to discuss it with hhh. Maybe some post-install trigger to run _apt-get update/upgrade_?

The first run of _bl-welcome_ will bring in the new **bunsen-configs**, but the patch will go into the file in skel/. Users will still have to edit their personal copy of menu.xml, or initiate an overwrite of their config files by deleting ~/.config/bunsen/bl-setup and logging out/in.

We just have to be super-careful to minimize changes to the template user config files in skel. It's unfortunate that this bug got through just before the official release. (Luckily the paths in the "help" submenu are OK.)

**Comment by ghost** [comment]
Uusually, when installing Debian via netinstall, it will update the package index and download the latest packages of the base system before installing. I'm not familiar how the Debian installer and live environments work in that regard however, that's why I was asking. No problem as long as we deploy the symlink IMO.

**Comment by johnraff** [comment]
Right, the symlink (bunsen-docs>bunsen) takes effect immediately and needs no user action.
**bunsen-docs 8.1-2** now on GitHub.

**Comment by ghost** [comment]
Both changes are deployed to the repos.

**Comment by johnraff** [comment]
Thanks!
And apologies for that careless oversight.
