### ISSUE TITLE
Add subtle animations to compton.

### ISSUE THREAD

**Issue by hhhorb** [BunsenLabs/bunsen-configs#44]
In compton.conf, change...

```
# Fading
fading = false;
# fade-delta = 30;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;
```

... (or whatever it currently is) to...

```
# Fading
#fading = false;
# fade-delta = 30;
#fade-in-step = 0.03;
#fade-out-step = 0.03;
# no-fading-openclose = true;
fading = true;
fade-delta = 3;
```

... for a tiny bit of eyecandy.

**Comment by Sector11** [comment]
It is a subtle change.
I could get use to it.

**Comment by hhhorb** [comment]
^ Thanks for the feedback. I'll commit the change in a week if I don't hear anything else.

**Comment by johnraff** [comment]
I tried @hhhorb's config and all I could see was a slight delay before popups and menus appeared. I'd hardly classify it as "eye candy" to be honest.

Is there something more to it that I'm missing?

**Comment by hhhorb** [comment]
Leaving this issue alone for now.
