### ISSUE TITLE
lightdm: Set greeter-hide-users=false to show available users in greeter

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-configs#59]
Suggestion from https://forums.bunsenlabs.org/viewtopic.php?id=4313.

I think this is a good idea and fairly standard behaviour.

**Comment by hhhorb** [comment]
We had discussed this before and decided to set this to true for added security (hacker needs both password and username instead of just password).

I'm open for change, though. Certainly it's more convenient to just type your password.

**Comment by johnraff** [comment]
`greeter-hide-users=false` is the Debian default (set, as hathor said, in `/usr/share/lightdm/lightdm.conf.d/01_debian.conf`) but they always take the most conservative option and leave it to sysadmins to loosen up if they want.

That's good policy for *Debian* IMO, but for BL I have no objection either to displaying usernames on the login as our default. As 2ion says, it's fairly standard elsewhere, and easy enough to change if admins want to turn it off.

We can add the setting to  `usr/share/lightdm/lightdm.conf.d/50_bunsen-ldm.conf` and it will override Debian's.

**Comment by hhhorb** [comment]
I'm fine with this. I think we should make the change since the issue has been raised more than once, I bet we'll get nobody asking to revert the behavior.

**Comment by ghost** [comment]
To me, this is a papercut bug which goes against expected behaviour.

E.g. this is the behaviour on Windows, OSX, sddm, gdm (conceeding xdm :).

Certainly it makes little difference on a 1-personal computer, but if
e.g. 4 family members (some non-technical) use the computer, a greeter
with a user roster would be helpful.

**Comment by hhhorb** [comment]
That's 3 yea votes. Triumverate? :D
