### ISSUE TITLE
Update bl-mpv for mpv=0.23 and provide skel/.config/mpv/mpv.conf

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-configs#64]
* Various options used in bl-mpv are not longer available in version 0.23 of the player as shipped in stretch.
 * Various hackery in bl-mpv can be done away with by deploying a mpv configuration file or simplified by using mpv profiles.

I'll take care of this shortly. Leaving this note to not let it be forgotten.

**Comment by johnraff** [comment]
Thanks! 
Checking out bl-mpv in Stretch was *next-but-one* on my to-do list, but as you're more familiar with mpv than me I'm most happy to leave it in your hands.

btw: maybe consider /etc/mpv/mpv.conf as an alternative to skel? That would allow improvements to the default settings via package upgrades.
EDIT: But it would seem the lua options for the O.S.C. can only be set via ~/.config/mpv/lua-settings/osc.conf, not in /etc

Anyway, よろしく！

**Comment by ghost** [comment]
OSC configuration can be passed in via the script-opts= configuration file setting (at least in 0.27, and hopefully in 0.23, the option is available). I've pushed a basic config on the branch [helium-dev-mpv](https://github.com/BunsenLabs/bunsen-configs/tree/helium-dev-mpv) and am going to test it on a stretch install shortly (have to make a VM for that).
