### ISSUE TITLE
/grub2/i386-pc/normal.mod not Found when Booting HELIUM5 AMD64 Installation from an USB-drive

### ISSUE THREAD

**Issue by martinvahi** [BunsenLabs/bunsen-configs#95]
Reproduction:

Run the HELIUM5 AMD64 installation program from a DVD and choose an USB-drive as the target for installation. Choose the bootloader location to be on the USB-drive in stead of the built-in HDD.

The ~15GiB sized USB-drive had the following partitions:

    primary_partition_1) SWAP

    primary_partition_2) About 600MiB /boot with a bootable flag set, ext4 with noatime set

    primary_partition_3) /  fills out the rest of the USB-drive.

I do not know, if that's the right GitHub repository for filing this bug report, but I had to choose some repository, so I thought that may be this one will do.

Thank You for reading my comment/bug_report.

**Comment by johnraff** [comment]
BunsenLabs Helium is now obsolete.
Please post a new issue if the problem persists with the latest release.
Closing.
